version: '3.9'

services:
  client:
    container_name: client-container
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/app"
      - "./client/node_modules:/src/node_modules"
    stdin_open: true
  server:
    environment:
      DB_CONNECT: mongodb://mongo:27017/HappyNotes
    container_name: server-container
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/src
      - ./server/node_modules:/src/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"